//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsClient.ProductsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductData", Namespace="http://schemas.datacontract.org/2004/07/Products")]
    public partial class ProductData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ColorField;
        
        private decimal ListPriceField;
        
        private string NameField;
        
        private string ProductNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice
        {
            get
            {
                return this.ListPriceField;
            }
            set
            {
                this.ListPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber
        {
            get
            {
                return this.ProductNumberField;
            }
            set
            {
                this.ProductNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adventure-works.com/2010/07/22", ConfigurationName="ProductsClient.ProductsService.ProductsService", CallbackContract=typeof(ProductsClient.ProductsService.ProductsServiceCallback))]
    public interface ProductsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2010/07/22/ProductsService/ListProducts", ReplyAction="http://adventure-works.com/2010/07/22/ProductsService/ListProductsResponse")]
        string[] ListProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2010/07/22/ProductsService/GetProduct", ReplyAction="http://adventure-works.com/2010/07/22/ProductsService/GetProductResponse")]
        ProductsClient.ProductsService.ProductData GetProduct(string productNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2010/07/22/ProductsService/CurrentStockLevel", ReplyAction="http://adventure-works.com/2010/07/22/ProductsService/CurrentStockLevelResponse")]
        int CurrentStockLevel(string productNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2010/07/22/ProductsService/ChangeStockLevel", ReplyAction="http://adventure-works.com/2010/07/22/ProductsService/ChangeStockLevelResponse")]
        bool ChangeStockLevel(string productNumber, short newStockLevel, string shelf, int bin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2010/07/22/ProductsService/ChangePrice", ReplyAction="http://adventure-works.com/2010/07/22/ProductsService/ChangePriceResponse")]
        void ChangePrice(string productNumber, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2010/07/22/ProductsService/SubscribeToPriceChangedEven" +
            "t", ReplyAction="http://adventure-works.com/2010/07/22/ProductsService/SubscribeToPriceChangedEven" +
            "tResponse")]
        bool SubscribeToPriceChangedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure-works.com/2010/07/22/ProductsService/UnsubscribeFromPriceChanged" +
            "Event", ReplyAction="http://adventure-works.com/2010/07/22/ProductsService/UnsubscribeFromPriceChanged" +
            "EventResponse")]
        bool UnsubscribeFromPriceChangedEvent();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductsServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://adventure-works.com/2010/07/22/ProductsService/OnPriceChanged")]
        void OnPriceChanged(ProductsClient.ProductsService.ProductData product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductsServiceChannel : ProductsClient.ProductsService.ProductsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsServiceClient : System.ServiceModel.DuplexClientBase<ProductsClient.ProductsService.ProductsService>, ProductsClient.ProductsService.ProductsService
    {
        
        public ProductsServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public ProductsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public ProductsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductsServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public string[] ListProducts()
        {
            return base.Channel.ListProducts();
        }
        
        public ProductsClient.ProductsService.ProductData GetProduct(string productNumber)
        {
            return base.Channel.GetProduct(productNumber);
        }
        
        public int CurrentStockLevel(string productNumber)
        {
            return base.Channel.CurrentStockLevel(productNumber);
        }
        
        public bool ChangeStockLevel(string productNumber, short newStockLevel, string shelf, int bin)
        {
            return base.Channel.ChangeStockLevel(productNumber, newStockLevel, shelf, bin);
        }
        
        public void ChangePrice(string productNumber, decimal price)
        {
            base.Channel.ChangePrice(productNumber, price);
        }
        
        public bool SubscribeToPriceChangedEvent()
        {
            return base.Channel.SubscribeToPriceChangedEvent();
        }
        
        public bool UnsubscribeFromPriceChangedEvent()
        {
            return base.Channel.UnsubscribeFromPriceChangedEvent();
        }
    }
}
